//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "article_launches")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub article_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub launch_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::articles::Entity",
        from = "Column::ArticleId",
        to = "super::articles::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Articles,
    #[sea_orm(
        belongs_to = "super::launches::Entity",
        from = "Column::LaunchId",
        to = "super::launches::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Launches,
}

impl Related<super::articles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Articles.def()
    }
}

impl Related<super::launches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Launches.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
