//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "articles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub title: String,
    pub url: Option<String>,
    pub image_url: Option<String>,
    pub news_site: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub summary: Option<String>,
    pub published_at: DateTime,
    pub updated_at: DateTime,
    pub featured: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::article_authors::Entity")]
    ArticleAuthors,
    #[sea_orm(has_many = "super::article_events::Entity")]
    ArticleEvents,
    #[sea_orm(has_many = "super::article_launches::Entity")]
    ArticleLaunches,
}

impl Related<super::article_authors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArticleAuthors.def()
    }
}

impl Related<super::article_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArticleEvents.def()
    }
}

impl Related<super::article_launches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArticleLaunches.def()
    }
}

impl Related<super::authors::Entity> for Entity {
    fn to() -> RelationDef {
        super::article_authors::Relation::Authors.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::article_authors::Relation::Articles.def().rev())
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        super::article_events::Relation::Events.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::article_events::Relation::Articles.def().rev())
    }
}

impl Related<super::launches::Entity> for Entity {
    fn to() -> RelationDef {
        super::article_launches::Relation::Launches.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::article_launches::Relation::Articles.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
