//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "authors")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::article_authors::Entity")]
    ArticleAuthors,
    #[sea_orm(has_one = "super::author_socials::Entity")]
    AuthorSocials,
    #[sea_orm(has_many = "super::blog_authors::Entity")]
    BlogAuthors,
    #[sea_orm(has_many = "super::report_authors::Entity")]
    ReportAuthors,
}

impl Related<super::article_authors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArticleAuthors.def()
    }
}

impl Related<super::author_socials::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthorSocials.def()
    }
}

impl Related<super::blog_authors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogAuthors.def()
    }
}

impl Related<super::report_authors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReportAuthors.def()
    }
}

impl Related<super::articles::Entity> for Entity {
    fn to() -> RelationDef {
        super::article_authors::Relation::Articles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::article_authors::Relation::Authors.def().rev())
    }
}

impl Related<super::blogs::Entity> for Entity {
    fn to() -> RelationDef {
        super::blog_authors::Relation::Blogs.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::blog_authors::Relation::Authors.def().rev())
    }
}

impl Related<super::reports::Entity> for Entity {
    fn to() -> RelationDef {
        super::report_authors::Relation::Reports.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::report_authors::Relation::Authors.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
