//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "blog_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub blog_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub event_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::blogs::Entity",
        from = "Column::BlogId",
        to = "super::blogs::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Blogs,
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Events,
}

impl Related<super::blogs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Blogs.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
