//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "blogs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub title: String,
    pub url: Option<String>,
    pub image_url: Option<String>,
    pub news_site: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub summary: Option<String>,
    pub published_at: DateTime,
    pub updated_at: DateTime,
    pub featured: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::blog_authors::Entity")]
    BlogAuthors,
    #[sea_orm(has_many = "super::blog_events::Entity")]
    BlogEvents,
    #[sea_orm(has_many = "super::blog_launches::Entity")]
    BlogLaunches,
}

impl Related<super::blog_authors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogAuthors.def()
    }
}

impl Related<super::blog_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogEvents.def()
    }
}

impl Related<super::blog_launches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogLaunches.def()
    }
}

impl Related<super::authors::Entity> for Entity {
    fn to() -> RelationDef {
        super::blog_authors::Relation::Authors.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::blog_authors::Relation::Blogs.def().rev())
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        super::blog_events::Relation::Events.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::blog_events::Relation::Blogs.def().rev())
    }
}

impl Related<super::launches::Entity> for Entity {
    fn to() -> RelationDef {
        super::blog_launches::Relation::Launches.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::blog_launches::Relation::Blogs.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
