//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "events")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub external_id: Option<i32>,
    pub name: Option<String>,
    pub provider: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::article_events::Entity")]
    ArticleEvents,
    #[sea_orm(has_many = "super::blog_events::Entity")]
    BlogEvents,
    #[sea_orm(has_many = "super::report_events::Entity")]
    ReportEvents,
}

impl Related<super::article_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArticleEvents.def()
    }
}

impl Related<super::blog_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogEvents.def()
    }
}

impl Related<super::report_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReportEvents.def()
    }
}

impl Related<super::articles::Entity> for Entity {
    fn to() -> RelationDef {
        super::article_events::Relation::Articles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::article_events::Relation::Events.def().rev())
    }
}

impl Related<super::blogs::Entity> for Entity {
    fn to() -> RelationDef {
        super::blog_events::Relation::Blogs.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::blog_events::Relation::Events.def().rev())
    }
}

impl Related<super::reports::Entity> for Entity {
    fn to() -> RelationDef {
        super::report_events::Relation::Reports.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::report_events::Relation::Events.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
