//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "launches")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub external_id: Option<i32>,
    pub name: Option<String>,
    pub provider: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::article_launches::Entity")]
    ArticleLaunches,
    #[sea_orm(has_many = "super::blog_launches::Entity")]
    BlogLaunches,
    #[sea_orm(has_many = "super::report_launches::Entity")]
    ReportLaunches,
}

impl Related<super::article_launches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArticleLaunches.def()
    }
}

impl Related<super::blog_launches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlogLaunches.def()
    }
}

impl Related<super::report_launches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReportLaunches.def()
    }
}

impl Related<super::articles::Entity> for Entity {
    fn to() -> RelationDef {
        super::article_launches::Relation::Articles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::article_launches::Relation::Launches.def().rev())
    }
}

impl Related<super::blogs::Entity> for Entity {
    fn to() -> RelationDef {
        super::blog_launches::Relation::Blogs.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::blog_launches::Relation::Launches.def().rev())
    }
}

impl Related<super::reports::Entity> for Entity {
    fn to() -> RelationDef {
        super::report_launches::Relation::Reports.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::report_launches::Relation::Launches.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
