//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "reports")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub title: String,
    pub url: Option<String>,
    pub image_url: Option<String>,
    pub news_site: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub summary: Option<String>,
    pub published_at: DateTime,
    pub updated_at: DateTime,
    pub featured: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::report_authors::Entity")]
    ReportAuthors,
    #[sea_orm(has_many = "super::report_events::Entity")]
    ReportEvents,
    #[sea_orm(has_many = "super::report_launches::Entity")]
    ReportLaunches,
}

impl Related<super::report_authors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReportAuthors.def()
    }
}

impl Related<super::report_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReportEvents.def()
    }
}

impl Related<super::report_launches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReportLaunches.def()
    }
}

impl Related<super::authors::Entity> for Entity {
    fn to() -> RelationDef {
        super::report_authors::Relation::Authors.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::report_authors::Relation::Reports.def().rev())
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        super::report_events::Relation::Events.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::report_events::Relation::Reports.def().rev())
    }
}

impl Related<super::launches::Entity> for Entity {
    fn to() -> RelationDef {
        super::report_launches::Relation::Launches.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::report_launches::Relation::Reports.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
